---
# tasks file for authentication
- name: Install required packages
  yum:
    name: "{{ item }}"
  with_items: "{{ packages_to_install }}"

- name: installing pip packages
  pip:
    name: "{{ item }}"
    state: present
    extra_args: "--trusted-host pypi.python.org"
  with_items: "{{ pip_packages }}"

- name: install CA certificate
  copy:
    content: "{{ ca_cert }}"
    dest: "{{ ca_cert_location }}/dev-net-root.crt"
    owner: root
    group: root
    mode: '0644'
  notify: update trust

- name: Check domain membership status
  shell: /bin/bash -c "realm list | grep sssd"
  register: realm_bound
  changed_when: False
  ignore_errors: True

- name: Join the domain
  expect:
    command: "/bin/bash -c '/usr/sbin/realm join -U {{ bind_user }} {{ realm }}'"
    responses:
      Password for.*: "{{ bind_password }}"
  when: realm_bound.rc != '0'

- name: Configure sssd
  template:
    src: sssd.j2
    dest: /etc/sssd/sssd.conf
    group: root
    owner: root
    mode: 0600
  notify: restart sssd

- name: Enable required services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ enabled_services }}"

